markdown: kramdown
highlighter: rouge
title: r3aper's blog
tagline: A Jekyll theme
description: 'Development, programmer tips'
url: 'https://reaper.github.io'
baseurl: /
author:
  name: Pierre FILSTROFF
  url: 'https://twitter.com/reaper67'
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
sidebar_home_link: true
